PARAMS = {
  STRING: 'STRING',
  INTEGER: 'INTEGER',
  DATE: 'DATE',
  UNIXTIMESTAMP: 'UNIXTIMESTAMP',
  DOMAIN: 'DOMAIN',
  IP: 'IP',
  DOMAINORIP: 'DOMAINORIP',
  DOUBLE: 'DOUBLE',
  UNSIGNED_SHORT: 'UNSIGNED_SHORT',
  NUMBER: 'NUMBER',
  BASE64: 'BASE64',
  BOOLEAN: 'BOOLEAN'
};

